#!/bin/bash

# Setup do FitLoop Backend
# Este script configuraseu banco de dados no Supabase

echo "🚀 Setup FitLoop Backend"
echo ""
echo "Como usar:"
echo ""
echo "1️⃣  Configure o arquivo .env (já está pronto):"
echo "   - SUPABASE_URL"
echo "   - SUPABASE_SERVICE_ROLE_KEY"
echo "   - BUCKET_NAME"
echo ""
echo "2️⃣  Crie as tabelas no Supabase:"
echo ""
echo "   Opção A: Copiar e colar (mais fácil)"
echo "   ────────────────────────────────"
echo "   1. Abra: https://supabase.com/dashboard/project/_/sql/new"
echo "   2. Cole o conteúdo de: src/migrations/schema.sql"
echo "   3. Clique em 'Run'"
echo ""
echo "   Opção B: Arquivo (se tiver psql instalado)"
echo "   ──────────────────────────────────────────"
echo "   psql -h seu-projeto.supabase.co -U postgres -d postgres -f src/migrations/schema.sql"
echo ""
echo "3️⃣  Após criar as tabelas:"
echo ""
echo "   npm install"
echo "   npm run dev"
echo ""
echo "4️⃣  (Opcional) Inserir dados de exemplo:"
echo ""
echo "   npm run seed:sites"
echo ""
